language: node_js
node_js:
- '0.11'
before_install:
- npm install browserify -g
install:
- npm install
before_script:
- npm link .
script:
- ./ci/build.js
- ./ci/test.js
- ./ci/cover.js
- ./ci/report.js
env:
  global:
    secure: hKQZar6ikMCdlYePXJ1RMU/avPDzllSLheodci3F3ZNSSa6U8WL1lRmwfQpJBrSdGwyK2OyJYhOQFp1kRwc2Z/216asVRZf28ILYMVdQYiGIX6fwB7b5f/fVwBjGDzqQ9sIUGlAwo6XHMo7o6gmNVgdow1Je3293CU29H1xhI9XdslQR6m+yQmLrqMkJfRLQWr04pGCzTXdGuW73HsPM88fFIgLqYLL+wdLbRqr1iumVWSl0BQQl2nhDLW9qcB81KJJ54dBVXMd7pEN//k8V8FzcceCvquiowaifA0O2sByBarC0EFa/wcHuO55mrL4IB4frxrtR2WM5svyr9zb1lCxq2vt3wpfBm4uST9HX38eJreDlTH9zqEHMLlCgln2D3gQXdsNuPvM3vp6kAekz/BWnm/ACsKOjZrhF00K+soI5KmClkNyJ+WBPg1MBvrhb4b28AUOSsI/rwbe00YOAyJQLKBB1uz8oa+KNwSKVB47IhnfvVjf+frRbGPNYVgpeAqd4nWAI1DelR1Wr28pSNfgVHWld0k13V8DzMvQ3ruEgJQ0mxaPQ8IvXxlkO8rgEur6RmeWw/8C1nAa1VmI6hh0rWkrkDNwMVEz58cKN0QJfwOAdaCrIg7dOiz3tjnwcYvv3HCszeHMBfzI2I2Rnu7IHHU9RALTeeZZixKqex2I=
